[project]
name = "pptx-image-align"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-pptx>=1.0.2",
    "pyyaml>=6.0.3",
]
